### PR TITLE
Use new colours for logo, use grayscale backdrop

### PR DESCRIPTION
**Pull request by calvin-brizzi**
Use the new logo, change the background image to grayscale

### CODE REVIEW

**Comment by calvin-brizzi** [comment]
Screenshot 2019-11-28 at 22 10 11

**Comment by MarijeP** [comment]
Ja, :+1: @vhata @duncanphillips any comments or can we push and carry on? I'll update with the red logo as per #355

**Comment by vhata** [comment]
This looks good to me.

**Comment by vhata** [comment]
I like it 👍

**Pull request merged**
