### PR TITLE
Add OfferZen

### PR DESCRIPTION
**Pull request by MarijeP**
Those tags are weird on sponsors.yml, so not consistent. Want to tell me what the right way is and I’ll fix them?

Anyway, hoping I’ve done everything right here.

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@MarijeP missing images?

**Comment by adrianmoisey** [comment]
Looks funky:
image

**Comment by adrianmoisey** [comment]
Images can be compressed a bit (50%), pass them through https://imageoptim.com/ first.

**Comment by adrianmoisey** [comment]
Looks betterer:
image

**Pull request merged**
