### PR TITLE
Update /speakers

### PR DESCRIPTION
**Pull request by imsickofmaps**
Update the page to include all previous speakers. We'll need to organise it - by conference date?

***

> With a mixture of African and international speakers, we're bringing a diversity of experience and perspective to the stage. Meet the engineers who will share their war stories.

Change to:

> With a mixture of African and international speakers, ScaleConf brings a diversity of experience and perspective to the stage. Meet the speakers who have shared their war stories.

***

> Previous speakers with videos and slides can be found here (http://scaleconf.org/videos).

***

*List the past speakers*

### Business of Scale

Franz Struwig
Mark Forrester
...etc

### Technology of Scale

Charity Majors
Matty Cohen
...etc

## 2012

### CODE REVIEW

**Comment by imsickofmaps** [comment]
Ready for review

**Comment by adrianmoisey** [comment]
I feel like this could get a massive cleanup. Could be way DRYer.
But it works for now: :+1:

Also, it would be nice to get 2012 on that list too.

**Comment by imsickofmaps** [comment]
ja. The only reason I didn't DRY it up was because of the shift to split biz/tech.

**Comment by vhata** [comment]
It would have been easy enough to do:

```
for year in years:
   if bizness:  do bizness
   if tek:  do tek
```

**Pull request merged**
