### PR TITLE
Sponsors in footer

### PR DESCRIPTION
**Pull request by duncanphillips**
Just a first attempt / working branch for putting sponsors in the footer of the website (as per baseline). I'm not sure how we can make this prettier, but we probably need to fix up the logo sizes - https://github.com/scaleconf/scaleconf.github.com/issues/135

### CODE REVIEW

**Comment by duncanphillips** [comment]
screen shot 2015-02-03 at 9 28 02 pm

**Comment by duncanphillips** [comment]
also requires takealot resources/info

**Comment by imsickofmaps** [comment]
@vhata / @duncanphillips ready for review again

screenshot 2015-02-07 20 44 18

**Comment by vhata** [comment]
The tickets-for-sale header now seems weird - it's not stuck to the top any more.  But otherwise :+1:

**Comment by imsickofmaps** [comment]
Yeah - I'm not a huge fan of the pushed down header esp on mobile but design is taste and taste is preference and ¯\_(ツ)_/¯

**Pull request merged**
